/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author juane
 */
public class AlgFrame extends javax.swing.JFrame {

	/**
	 * Creates new form AlgFrame
	 */
	public AlgFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_tittle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        label_instance_tittle1 = new javax.swing.JLabel();
        button_solve = new javax.swing.JButton();
        panel_results = new javax.swing.JPanel();
        label_instance_tittle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_cost = new javax.swing.JTextField();
        text_elapsed = new javax.swing.JTextField();
        button_print = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        label_instance_alg = new javax.swing.JLabel();
        button_back = new javax.swing.JButton();
        panel_mainPanel = new javax.swing.JPanel();
        panel_bl = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        text_evals_bl = new javax.swing.JTextPane();
        label_instance_tittle13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        check_bl = new javax.swing.JCheckBox();
        panel_es = new javax.swing.JPanel();
        label_instance_tittle10 = new javax.swing.JLabel();
        panel_es_es = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        text_redneighs_es = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        text_mults_es = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        text_mu_es = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        text_theta_es = new javax.swing.JTextPane();
        panel_es_bl1 = new javax.swing.JPanel();
        jScrollPane31 = new javax.swing.JScrollPane();
        text_evals_es = new javax.swing.JTextPane();
        jLabel20 = new javax.swing.JLabel();
        panel_bmb = new javax.swing.JPanel();
        label_instance_tittle2 = new javax.swing.JLabel();
        panel_bmb_bl = new javax.swing.JPanel();
        check_bmb_bl = new javax.swing.JCheckBox();
        jScrollPane22 = new javax.swing.JScrollPane();
        text_evals_bmb = new javax.swing.JTextPane();
        jLabel22 = new javax.swing.JLabel();
        panel_bmb_bmb = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_iters_bmb = new javax.swing.JTextPane();
        panel_ils = new javax.swing.JPanel();
        label_instance_tittle3 = new javax.swing.JLabel();
        panel_ils_bl = new javax.swing.JPanel();
        check_ils_bl = new javax.swing.JCheckBox();
        jScrollPane24 = new javax.swing.JScrollPane();
        text_evals_ils = new javax.swing.JTextPane();
        jLabel23 = new javax.swing.JLabel();
        panel_ils_ils = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        text_iters_ils = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        text_redsubl_ils = new javax.swing.JTextPane();
        panel_ilses = new javax.swing.JPanel();
        label_instance_tittle14 = new javax.swing.JLabel();
        panel_ils_bl1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        text_evals_ilses = new javax.swing.JTextPane();
        panel_es_es1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane30 = new javax.swing.JScrollPane();
        text_redn_ilses = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        text_mults_ilses = new javax.swing.JTextPane();
        jScrollPane29 = new javax.swing.JScrollPane();
        text_mu_ilses = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        text_theta_ilses = new javax.swing.JTextPane();
        panel_ils_ils1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        text_redsubl_ilses = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        text_iters_ilses = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("choose algorithm");
        setMinimumSize(new java.awt.Dimension(760, 495));
        setName("choose"); // NOI18N
        setPreferredSize(new java.awt.Dimension(710, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_tittle.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        label_tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tittle.setText("QAP PROBLEM");
        getContentPane().add(label_tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 330, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 30));

        label_instance_tittle1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle1.setText("Choose Algorithm");
        getContentPane().add(label_instance_tittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 20));

        button_solve.setText("SOLVE!");
        getContentPane().add(button_solve, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, 40));

        panel_results.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        label_instance_tittle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        label_instance_tittle.setText("RESULTS");

        jLabel4.setText("Time elapsed: ");

        jLabel5.setText("Solution Cost:");

        text_cost.setFocusable(false);

        text_elapsed.setFocusable(false);

        button_print.setText("Print Solution!");

        jLabel6.setText("Instance: ");

        javax.swing.GroupLayout panel_resultsLayout = new javax.swing.GroupLayout(panel_results);
        panel_results.setLayout(panel_resultsLayout);
        panel_resultsLayout.setHorizontalGroup(
            panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultsLayout.createSequentialGroup()
                .addGroup(panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_resultsLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(label_instance_tittle))
                    .addGroup(panel_resultsLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(button_print))
                    .addGroup(panel_resultsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_cost)
                            .addComponent(text_elapsed, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(label_instance_alg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panel_resultsLayout.setVerticalGroup(
            panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(label_instance_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(label_instance_alg, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_elapsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(panel_resultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_cost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_print)
                .addGap(24, 24, 24))
        );

        getContentPane().add(panel_results, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, 220));

        button_back.setText("BACK");
        getContentPane().add(button_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, -1));

        panel_mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_mainPanel.setLayout(new java.awt.CardLayout());

        panel_bl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("MAX EVALS:");

        text_evals_bl.setText("50000");
        jScrollPane23.setViewportView(text_evals_bl);

        label_instance_tittle13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle13.setText("Parameters");

        jLabel27.setText("DLB");

        check_bl.setSelected(true);

        javax.swing.GroupLayout panel_blLayout = new javax.swing.GroupLayout(panel_bl);
        panel_bl.setLayout(panel_blLayout);
        panel_blLayout.setHorizontalGroup(
            panel_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_blLayout.createSequentialGroup()
                .addGroup(panel_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_blLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panel_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_blLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(check_bl))
                            .addGroup(panel_blLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_blLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_instance_tittle13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        panel_blLayout.setVerticalGroup(
            panel_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_blLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_instance_tittle13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_bl))
                .addContainerGap(304, Short.MAX_VALUE))
        );

        panel_mainPanel.add(panel_bl, "card_BL");

        panel_es.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_instance_tittle10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle10.setText("Parameters");

        panel_es_es.setBorder(javax.swing.BorderFactory.createTitledBorder("ES"));

        jLabel29.setText("theta");

        jLabel28.setText("mu");

        jLabel30.setText("mult. size");

        jLabel31.setText("reduction neighs");

        text_redneighs_es.setText("0.1");
        jScrollPane25.setViewportView(text_redneighs_es);

        text_mults_es.setText("10");
        jScrollPane27.setViewportView(text_mults_es);

        text_mu_es.setText("0.3");
        jScrollPane20.setViewportView(text_mu_es);

        text_theta_es.setText("0.3");
        jScrollPane19.setViewportView(text_theta_es);

        javax.swing.GroupLayout panel_es_esLayout = new javax.swing.GroupLayout(panel_es_es);
        panel_es_es.setLayout(panel_es_esLayout);
        panel_es_esLayout.setHorizontalGroup(
            panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_es_esLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_es_esLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_es_esLayout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_es_esLayout.createSequentialGroup()
                        .addGroup(panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_es_esLayout.setVerticalGroup(
            panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_es_esLayout.createSequentialGroup()
                .addGroup(panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_es_esLayout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_es_esLayout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_es_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panel_es_bl1.setBorder(javax.swing.BorderFactory.createTitledBorder("BL"));
        panel_es_bl1.setToolTipText("BL");
        panel_es_bl1.setPreferredSize(new java.awt.Dimension(580, 65));

        text_evals_es.setText("50000");
        jScrollPane31.setViewportView(text_evals_es);

        jLabel20.setText("MAX EVALS");

        javax.swing.GroupLayout panel_es_bl1Layout = new javax.swing.GroupLayout(panel_es_bl1);
        panel_es_bl1.setLayout(panel_es_bl1Layout);
        panel_es_bl1Layout.setHorizontalGroup(
            panel_es_bl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_es_bl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        panel_es_bl1Layout.setVerticalGroup(
            panel_es_bl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_es_bl1Layout.createSequentialGroup()
                .addGroup(panel_es_bl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_es_bl1Layout.createSequentialGroup()
                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_esLayout = new javax.swing.GroupLayout(panel_es);
        panel_es.setLayout(panel_esLayout);
        panel_esLayout.setHorizontalGroup(
            panel_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_esLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_es_es, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_esLayout.createSequentialGroup()
                        .addComponent(label_instance_tittle10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel_es_bl1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_esLayout.setVerticalGroup(
            panel_esLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_esLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_instance_tittle10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_es_bl1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panel_es_es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panel_mainPanel.add(panel_es, "card_ES");

        panel_bmb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_instance_tittle2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle2.setText("Parameters");

        panel_bmb_bl.setBorder(javax.swing.BorderFactory.createTitledBorder("BL"));
        panel_bmb_bl.setToolTipText("BMB");
        panel_bmb_bl.setPreferredSize(new java.awt.Dimension(580, 65));

        check_bmb_bl.setSelected(true);
        check_bmb_bl.setText("DLB");

        text_evals_bmb.setText("50000");
        jScrollPane22.setViewportView(text_evals_bmb);

        jLabel22.setText("MAX EVALS");

        javax.swing.GroupLayout panel_bmb_blLayout = new javax.swing.GroupLayout(panel_bmb_bl);
        panel_bmb_bl.setLayout(panel_bmb_blLayout);
        panel_bmb_blLayout.setHorizontalGroup(
            panel_bmb_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bmb_blLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_bmb_bl)
                .addGap(297, 297, 297))
        );
        panel_bmb_blLayout.setVerticalGroup(
            panel_bmb_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bmb_blLayout.createSequentialGroup()
                .addGroup(panel_bmb_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_bmb_blLayout.createSequentialGroup()
                        .addGroup(panel_bmb_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_bmb_bl))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_bmb_bmb.setBorder(javax.swing.BorderFactory.createTitledBorder("BMB"));

        jLabel2.setText("MAX ITERS");

        text_iters_bmb.setText("25");
        jScrollPane2.setViewportView(text_iters_bmb);

        javax.swing.GroupLayout panel_bmb_bmbLayout = new javax.swing.GroupLayout(panel_bmb_bmb);
        panel_bmb_bmb.setLayout(panel_bmb_bmbLayout);
        panel_bmb_bmbLayout.setHorizontalGroup(
            panel_bmb_bmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bmb_bmbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        panel_bmb_bmbLayout.setVerticalGroup(
            panel_bmb_bmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bmb_bmbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bmb_bmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_bmbLayout = new javax.swing.GroupLayout(panel_bmb);
        panel_bmb.setLayout(panel_bmbLayout);
        panel_bmbLayout.setHorizontalGroup(
            panel_bmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bmbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_bmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_bmb_bmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_bmbLayout.createSequentialGroup()
                        .addComponent(label_instance_tittle2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel_bmb_bl, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_bmbLayout.setVerticalGroup(
            panel_bmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bmbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_instance_tittle2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_bmb_bl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_bmb_bmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        panel_mainPanel.add(panel_bmb, "card_BMB");

        panel_ils.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_instance_tittle3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle3.setText("Parameters");

        panel_ils_bl.setBorder(javax.swing.BorderFactory.createTitledBorder("BL"));
        panel_ils_bl.setToolTipText("BMB");

        check_ils_bl.setSelected(true);
        check_ils_bl.setText("DLB");

        text_evals_ils.setText("50000");
        jScrollPane24.setViewportView(text_evals_ils);

        jLabel23.setText("MAX EVALS");

        javax.swing.GroupLayout panel_ils_blLayout = new javax.swing.GroupLayout(panel_ils_bl);
        panel_ils_bl.setLayout(panel_ils_blLayout);
        panel_ils_blLayout.setHorizontalGroup(
            panel_ils_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ils_blLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_ils_bl)
                .addGap(297, 297, 297))
        );
        panel_ils_blLayout.setVerticalGroup(
            panel_ils_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ils_blLayout.createSequentialGroup()
                .addGroup(panel_ils_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ils_blLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(check_ils_bl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_ils_ils.setBorder(javax.swing.BorderFactory.createTitledBorder("ILS"));

        jLabel9.setText("MAX  ITERS");

        text_iters_ils.setText("25");
        jScrollPane7.setViewportView(text_iters_ils);

        jLabel7.setText("reduction subl");

        text_redsubl_ils.setText("0.25");
        jScrollPane5.setViewportView(text_redsubl_ils);

        javax.swing.GroupLayout panel_ils_ilsLayout = new javax.swing.GroupLayout(panel_ils_ils);
        panel_ils_ils.setLayout(panel_ils_ilsLayout);
        panel_ils_ilsLayout.setHorizontalGroup(
            panel_ils_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ils_ilsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ils_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_ils_ilsLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_ils_ilsLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ils_ilsLayout.setVerticalGroup(
            panel_ils_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ils_ilsLayout.createSequentialGroup()
                .addGroup(panel_ils_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ils_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_ilsLayout = new javax.swing.GroupLayout(panel_ils);
        panel_ils.setLayout(panel_ilsLayout);
        panel_ilsLayout.setHorizontalGroup(
            panel_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ilsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_ils_ils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_ilsLayout.createSequentialGroup()
                        .addComponent(label_instance_tittle3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 182, Short.MAX_VALUE))
                    .addComponent(panel_ils_bl, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_ilsLayout.setVerticalGroup(
            panel_ilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ilsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_instance_tittle3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_ils_bl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_ils_ils, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        panel_mainPanel.add(panel_ils, "card_ILS");

        panel_ilses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        label_instance_tittle14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle14.setText("Parameters");

        panel_ils_bl1.setBorder(javax.swing.BorderFactory.createTitledBorder("BL"));
        panel_ils_bl1.setToolTipText("BMB");

        jLabel24.setText("MAX EVALS");

        text_evals_ilses.setText("50000");
        jScrollPane18.setViewportView(text_evals_ilses);

        javax.swing.GroupLayout panel_ils_bl1Layout = new javax.swing.GroupLayout(panel_ils_bl1);
        panel_ils_bl1.setLayout(panel_ils_bl1Layout);
        panel_ils_bl1Layout.setHorizontalGroup(
            panel_ils_bl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ils_bl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395))
        );
        panel_ils_bl1Layout.setVerticalGroup(
            panel_ils_bl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ils_bl1Layout.createSequentialGroup()
                .addGroup(panel_ils_bl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ils_bl1Layout.createSequentialGroup()
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(2, 12, Short.MAX_VALUE))
        );

        panel_es_es1.setBorder(javax.swing.BorderFactory.createTitledBorder("ES"));

        jLabel39.setText("theta");

        jLabel40.setText("mu");

        jLabel41.setText("mult. size");

        jLabel42.setText("reduction neighs");

        text_redn_ilses.setText("0.1");
        jScrollPane30.setViewportView(text_redn_ilses);

        text_mults_ilses.setText("10");
        jScrollPane26.setViewportView(text_mults_ilses);

        text_mu_ilses.setText("0.3");
        jScrollPane29.setViewportView(text_mu_ilses);

        text_theta_ilses.setText("0.3");
        jScrollPane28.setViewportView(text_theta_ilses);

        javax.swing.GroupLayout panel_es_es1Layout = new javax.swing.GroupLayout(panel_es_es1);
        panel_es_es1.setLayout(panel_es_es1Layout);
        panel_es_es1Layout.setHorizontalGroup(
            panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_es_es1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_es_es1Layout.createSequentialGroup()
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_es_es1Layout.createSequentialGroup()
                        .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel_es_es1Layout.setVerticalGroup(
            panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_es_es1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_es_es1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_ils_ils1.setBorder(javax.swing.BorderFactory.createTitledBorder("ILS"));

        jLabel10.setText("MAX  ITERS");

        jLabel11.setText("reduction subl");

        text_redsubl_ilses.setText("0.25");
        jScrollPane6.setViewportView(text_redsubl_ilses);

        text_iters_ilses.setText("25");
        jScrollPane21.setViewportView(text_iters_ilses);

        javax.swing.GroupLayout panel_ils_ils1Layout = new javax.swing.GroupLayout(panel_ils_ils1);
        panel_ils_ils1.setLayout(panel_ils_ils1Layout);
        panel_ils_ils1Layout.setHorizontalGroup(
            panel_ils_ils1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ils_ils1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ils_ils1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_ils_ils1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panel_ils_ils1Layout.setVerticalGroup(
            panel_ils_ils1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ils_ils1Layout.createSequentialGroup()
                .addGroup(panel_ils_ils1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ils_ils1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panel_ilsesLayout = new javax.swing.GroupLayout(panel_ilses);
        panel_ilses.setLayout(panel_ilsesLayout);
        panel_ilsesLayout.setHorizontalGroup(
            panel_ilsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ilsesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ilsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ilsesLayout.createSequentialGroup()
                        .addComponent(label_instance_tittle14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel_ils_bl1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(panel_es_es1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ils_ils1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_ilsesLayout.setVerticalGroup(
            panel_ilsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ilsesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_instance_tittle14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_ils_bl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_es_es1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ils_ils1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_mainPanel.add(panel_ilses, "card_ILS_ES");

        getContentPane().add(panel_mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 350, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton button_back;
    public javax.swing.JButton button_print;
    public javax.swing.JButton button_solve;
    public javax.swing.JCheckBox check_bl;
    public javax.swing.JCheckBox check_bmb_bl;
    public javax.swing.JCheckBox check_ils_bl;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane18;
    public javax.swing.JScrollPane jScrollPane19;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    public javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    public javax.swing.JScrollPane jScrollPane24;
    public javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    public javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    public javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JLabel label_instance_alg;
    private javax.swing.JLabel label_instance_tittle;
    private javax.swing.JLabel label_instance_tittle1;
    private javax.swing.JLabel label_instance_tittle10;
    private javax.swing.JLabel label_instance_tittle13;
    private javax.swing.JLabel label_instance_tittle14;
    private javax.swing.JLabel label_instance_tittle2;
    private javax.swing.JLabel label_instance_tittle3;
    private javax.swing.JLabel label_tittle;
    public javax.swing.JPanel panel_bl;
    public javax.swing.JPanel panel_bmb;
    private javax.swing.JPanel panel_bmb_bl;
    private javax.swing.JPanel panel_bmb_bmb;
    public javax.swing.JPanel panel_es;
    private javax.swing.JPanel panel_es_bl1;
    private javax.swing.JPanel panel_es_es;
    private javax.swing.JPanel panel_es_es1;
    public javax.swing.JPanel panel_ils;
    private javax.swing.JPanel panel_ils_bl;
    private javax.swing.JPanel panel_ils_bl1;
    private javax.swing.JPanel panel_ils_ils;
    private javax.swing.JPanel panel_ils_ils1;
    public javax.swing.JPanel panel_ilses;
    public javax.swing.JPanel panel_mainPanel;
    private javax.swing.JPanel panel_results;
    public javax.swing.JTextField text_cost;
    public javax.swing.JTextField text_elapsed;
    public javax.swing.JTextPane text_evals_bl;
    public javax.swing.JTextPane text_evals_bmb;
    public javax.swing.JTextPane text_evals_es;
    public javax.swing.JTextPane text_evals_ils;
    public javax.swing.JTextPane text_evals_ilses;
    public javax.swing.JTextPane text_iters_bmb;
    public javax.swing.JTextPane text_iters_ils;
    public javax.swing.JTextPane text_iters_ilses;
    public javax.swing.JTextPane text_mu_es;
    public javax.swing.JTextPane text_mu_ilses;
    public javax.swing.JTextPane text_mults_es;
    public javax.swing.JTextPane text_mults_ilses;
    public javax.swing.JTextPane text_redn_ilses;
    public javax.swing.JTextPane text_redneighs_es;
    public javax.swing.JTextPane text_redsubl_ils;
    public javax.swing.JTextPane text_redsubl_ilses;
    public javax.swing.JTextPane text_theta_es;
    public javax.swing.JTextPane text_theta_ilses;
    // End of variables declaration//GEN-END:variables
}
