/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/**
 *
 * @author juane
 */
public class mainFrame extends javax.swing.JFrame {

	/**
	 * Creates new form mainFrame
	 */
	public mainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_tittle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_instance_tittle = new javax.swing.JLabel();
        jtext_instance = new javax.swing.JTextField();
        button_instance = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label_size_instance = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_instance_name = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        button_choose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GUI QAP");
        setMinimumSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_tittle.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        label_tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tittle.setText("QAP PROBLEM");
        getContentPane().add(label_tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 330, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_instance_tittle.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        label_instance_tittle.setText("Instance file");
        jPanel1.add(label_instance_tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jtext_instance.setToolTipText("");
        jPanel1.add(jtext_instance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 520, 30));

        button_instance.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        button_instance.setText("Browse..");
        jPanel1.add(button_instance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 660, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Name instance: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        label_size_instance.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        label_size_instance.setForeground(java.awt.Color.blue);
        label_size_instance.setText("0");
        jPanel2.add(label_size_instance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, 20));

        jLabel5.setText("Size problem:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 10));

        label_instance_name.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        label_instance_name.setForeground(java.awt.Color.blue);
        label_instance_name.setText("None");
        jPanel2.add(label_instance_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 10));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Instance loaded");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 330, 200));

        button_choose.setText("Choose algorithm");
        getContentPane().add(button_choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton button_choose;
    public javax.swing.JButton button_instance;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JTextField jtext_instance;
    public javax.swing.JLabel label_instance_name;
    private javax.swing.JLabel label_instance_tittle;
    public javax.swing.JLabel label_size_instance;
    private javax.swing.JLabel label_tittle;
    // End of variables declaration//GEN-END:variables
}
